id: P010765
initial_creation_type: ocr
source_metadata:
  id: bdr:W3CN8390
  title: འཇམ་དཔལ་དགེ་འདུན་རྒྱ་མཚོའི་རྣམ་ཐར།
  author: ''
  volumes:
    9e097092fda24bfdbc8eb3f25703fd1c:
      image_group_id: I3CN8392
      title: ''
      volume_number: 1
      total_pages: 126
